chore: Storage testing
relaycorp/awala-endpoint-android pull request #66
Opened 2021-03-16 15:44 UTC by sdsantos

2021-03-16 16:21 UTC, gnarea requested changes
Not sure if I'm missing something, but I don't think there are any tests to ensure sensitive data is encrypted at rest, right?

2021-03-17 12:08 UTC, sdsantos commented
> Not sure if I'm missing something, but I don't think there are any tests to ensure sensitive data is encrypted at rest, right?

That's the responsibility of `EncryptedDiskPersistenceTest`. This is just a unit test for the `StorageImpl` class.

2021-03-17 12:10 UTC, gnarea approved these changes
Good point

2021-03-17 12:11 UTC, gnarea approved these changes

2021-03-17 12:46 UTC, merged